server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Optional: backend proxy
    location /api/ {
        proxy_pass http://ems-backend:8080/;
    }
}